config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :friend_requests

      resources :comments

      resources :votes

      resources :photos

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "photos#index"
  resources :friend_requests
  resources :comments
  resources :votes
  resources :photos
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Direct associations
  has_many :access_grants,
           class_name: "Doorkeeper::AccessGrant",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: "Doorkeeper::AccessToken",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many   :recent_photos,
             -> { recent },
             class_name: "Photo",
             foreign_key: "owner_id",
             dependent: :destroy

  has_many   :accepted_sent_friend_requests,
             -> { accepted },
             class_name: "FriendRequest",
             foreign_key: "sender_id",
             dependent: :destroy

  has_many   :received_friend_requests,
             -> { not_pending },
             class_name: "FriendRequest",
             foreign_key: "recipient_id",
             dependent: :destroy

  has_many   :sent_friend_requests,
             class_name: "FriendRequest",
             foreign_key: "sender_id",
             dependent: :destroy

  has_many   :comments,
             foreign_key: "commenter_id",
             dependent: :destroy

  has_many   :likes,
             class_name: "Vote",
             dependent: :destroy

  has_many   :photos,
             foreign_key: "owner_id",
             dependent: :destroy

  # Indirect associations

  has_many   :followers,
             through: :received_friend_requests,
             source: :accepted_sender

  has_many   :following,
             through: :accepted_sent_friend_requests,
             source: :recipient

  has_many   :liked_photos,
             through: :likes,
             source: :photo

  has_many   :commented_photos,
             through: :comments,
             source: :photo

  # Validations

  validates :username, uniqueness: true

  validates :username, presence: true

  # Scopes

  def to_s
    first_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    base_scope = params[:id].blank? ? User.where(id: current_resource_owner) : User.all
    user = UserResource.find(params, base_scope)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @friend_request = FriendRequest.new
    @comment = Comment.new
    @vote = Vote.new
    @photo = Photo.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :avatar, :first_name, :last_name, :bio)
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Username</dt>
      <dd><%= user.username %></dd>

      <dt>Avatar</dt>
      <dd>
        <%= cl_image_tag @user.avatar, class: "img-fluid" %>
      </dd>

      <dt>First name</dt>
      <dd><%= user.first_name %></dd>

      <dt>Last name</dt>
      <dd><%= user.last_name %></dd>

      <dt>Bio</dt>
      <dd><%= user.bio %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_user_accepted_sent_friend_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Accepted Sent Friend Requests

    <a data-toggle="collapse" href="#user_accepted_sent_friend_requests_new_form">
      Add friend request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.accepted_sent_friend_requests.each do |friend_request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to friend_request.to_s, friend_request_path(friend_request) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_accepted_sent_friend_requests_new_form">
        <%= render partial: "users/user_accepted_sent_friend_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_accepted_sent_friend_requests_new_form.html.erb
<%= form_with(model: @friend_request, local: true) do |f| %>

  <%= f.hidden_field :sender_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :recipient_id %>
    <%= f.text_field :recipient_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(FriendRequest.statuses.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create friend request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :commenter_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :photo_id %>
    <%= f.collection_select :photo_id, Photo.all, :id, :to_s, {}, class: photo_class %>
  </div>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_liked_photos.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Liked Photos
  </div>

  <ul class="list-group list-group-flush">
    <% @user.liked_photos.each do |photo| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/photos/<%= photo.id %>">
          <%= photo.caption %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/users/_user_likes.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Likes

    <a data-toggle="collapse" href="#user_likes_new_form">
      Add vote
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.likes.each do |vote| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to vote.to_s, vote_path(vote) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_likes_new_form">
        <%= render partial: "users/user_likes_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_photos.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Photos

    <a data-toggle="collapse" href="#user_photos_new_form">
      Add photo
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.photos.each do |photo| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to photo.to_s, photo_path(photo) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_photos_new_form">
        <%= render partial: "users/user_photos_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_received_friend_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Received Friend Requests

    <a data-toggle="collapse" href="#user_received_friend_requests_new_form">
      Add friend request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.received_friend_requests.each do |friend_request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to friend_request.to_s, friend_request_path(friend_request) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_received_friend_requests_new_form">
        <%= render partial: "users/user_received_friend_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_received_friend_requests_new_form.html.erb
<%= form_with(model: @friend_request, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :sender_id %>
    <%= f.text_field :sender_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :recipient_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(FriendRequest.statuses.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create friend request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_recent_photos_new_form.html.erb
<%= form_with(model: @photo, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_field :caption, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <%= f.hidden_field :owner_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(Photo.statuses.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create photo", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_sent_friend_requests_new_form.html.erb
<%= form_with(model: @friend_request, local: true) do |f| %>

  <%= f.hidden_field :sender_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :recipient_id %>
    <%= f.text_field :recipient_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(FriendRequest.statuses.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create friend request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_photos" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_likes" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_sent_friend_requests" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_received_friend_requests" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_accepted_sent_friend_requests" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_recent_photos" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_commented_photos" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_liked_photos" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_following" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_followers" %>
  </div>
</div>