config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :friend_requests

      resources :comments

      resources :votes

      resources :photos

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "photos#index"
  resources :friend_requests
  resources :comments
  resources :votes
  resources :photos
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
require "open-uri"
class Photo < ApplicationRecord
  before_validation :geocode_location

  def geocode_location
    if location.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(location)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.location_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.location_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.location_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_uploader :image, ImageUploader

  enum status: { "recent" => 0, "old" => 1 }

  # Direct associations

  has_many   :comments,
             dependent: :destroy

  has_many   :likes,
             class_name: "Vote",
             dependent: :destroy

  belongs_to :recent_owner,
             class_name: "User",
             foreign_key: "owner_id"

  belongs_to :owner,
             optional: true,
             class_name: "User",
             counter_cache: true

  # Indirect associations

  has_many   :fans,
             through: :likes,
             source: :user

  has_many   :commenters,
             through: :comments,
             source: :commenter

  # Validations

  validates :image, presence: true

  validates :owner_id, presence: true

  # Scopes

  def to_s
    caption
  end
end

app/controllers/api/v1/photos_controller.rb
class Api::V1::PhotosController < Api::V1::GraphitiController
  def index
    photos = PhotoResource.all(params)
    respond_with(photos)
  end

  def show
    photo = PhotoResource.find(params)
    respond_with(photo)
  end

  def create
    photo = PhotoResource.build(params)

    if photo.save
      render jsonapi: photo, status: :created
    else
      render jsonapi_errors: photo
    end
  end

  def update
    photo = PhotoResource.find(params)

    if photo.update_attributes
      render jsonapi: photo
    else
      render jsonapi_errors: photo
    end
  end

  def destroy
    photo = PhotoResource.find(params)

    if photo.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: photo
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :current_user_must_be_photo_owner, only: %i[edit update destroy]

  before_action :set_photo, only: %i[show edit update destroy]

  def index
    @q = current_user.photos.ransack(params[:q])
    @photos = @q.result(distinct: true).includes(:owner, :recent_owner, :likes, :comments, :commenters, :fans).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@photos.where.not(location_latitude: nil)) do |photo, marker|
      marker.lat photo.location_latitude
      marker.lng photo.location_longitude
    end
  end

  def show
    @comment = Comment.new
    @vote = Vote.new
  end

  def new
    @photo = Photo.new
  end

  def edit; end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      message = "Photo was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @photo, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: "Photo was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    message = "Photo was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to photos_url, notice: message
    end
  end

  private

  def current_user_must_be_photo_owner
    set_photo
    unless current_user == @photo.owner
      redirect_back fallback_location: root_path, alert: "You are not authorized for that."
    end
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:caption, :image, :location, :owner_id, :status)
  end
end

app/views/photos/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Photo #<%= photo.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Caption</dt>
      <dd><%= photo.caption %></dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @photo.image, class: "img-fluid" %>
      </dd>

      <dt>Location</dt>
      <dd>
        <div>
          <%= render partial: "photos/one_photo_map" %>
        </div>
      </dd>

      <dt>Owner</dt>
      <dd><%= photo.owner_id %></dd>

      <dt>Status</dt>
      <dd><%= photo.status %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back photo, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @photo.owner %>
          <%= link_to edit_photo_url(photo), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @photo.owner %>
          <%= link_to photo, method: :delete, data: { confirm: "Do you really want to delete this photo?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(photo.updated_at) %> ago
  </div>
</div>

app/views/photos/_form.html.erb
<% was_validated = photo.errors.any? %>

<%= form_with(model: photo, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% caption_class = "form-control" %>
    <% caption_was_invalid = photo.errors.include?(:caption) %>

    <% if was_validated %>
      <% if caption_was_invalid %>
        <% caption_class << " is-invalid" %>
      <% else %>
        <% caption_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :caption %>
    <%= f.text_field :caption, class: caption_class, placeholder: "Enter caption" %>
    <% if caption_was_invalid %>
      <% photo.errors.full_messages_for(:caption).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = photo.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% photo.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% location_class = "form-control" %>
    <% location_was_invalid = photo.errors.include?(:location) %>

    <% if was_validated %>
      <% if location_was_invalid %>
        <% location_class << " is-invalid" %>
      <% else %>
        <% location_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :location %>
    <%= f.text_field :location, class: location_class, placeholder: "Enter location" %>
    <% if location_was_invalid %>
      <% photo.errors.full_messages_for(:location).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :owner_id, value: current_user.id %>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = photo.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status %>
    <%= f.select :status, options_for_select(Photo.statuses.keys), {}, class: "form-control" %>
    <% if status_was_invalid %>
      <% photo.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/photos/_list_item.html.erb
<%= link_to photo, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= photo.to_s %>
    <small class="text-muted">
      <%= time_ago_in_words(photo.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/photos/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @photo.location_latitude %>,
        "lng": <%= @photo.location_longitude %>,
        "infowindow": "<h5><%= @photo.created_at %></h5><small><%= @photo.location_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/photos/_photo_commenters.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Commenters
  </div>

  <ul class="list-group list-group-flush">
    <% @photo.commenters.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user.first_name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/photos/_photo_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Comments

    <a data-toggle="collapse" href="#photo_comments_new_form">
      Add comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @photo.comments.each do |comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to comment.to_s, comment_path(comment) %>

        <% if current_user == comment.commenter %>
          <%= link_to comment, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="photo_comments_new_form">
        <%= render partial: "photos/photo_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/photos/_photo_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :commenter_id, value: current_user.id %>

  <%= f.hidden_field :photo_id, value: @photo.id %>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/photos/_photo_fans.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Fans
  </div>

  <ul class="list-group list-group-flush">
    <% @photo.fans.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user.first_name %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/photos/_photo_likes_new_form.html.erb
<%= form_with(model: @vote, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.hidden_field :photo_id, value: @photo.id %>

  <%= f.submit "Create vote", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/photos/_photos_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "photos_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :caption_cont, "Caption contains" %>
    <%= f.text_field :caption_cont, :class => "form-control", :placeholder => "Caption contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :owner_first_name_cont, "User first_name contains" %>
    <%= f.text_field :owner_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :recent_owner_first_name_cont, "User first_name contains" %>
    <%= f.text_field :recent_owner_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :comments_body_cont, "Comment body contains" %>
    <%= f.text_field :comments_body_cont, :class => "form-control", :placeholder => "Comment body contains" %>
  </div>

  <div class="form-group">
    <%= f.label :commenters_first_name_cont, "User first_name contains" %>
    <%= f.text_field :commenters_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :fans_first_name_cont, "User first_name contains" %>
    <%= f.text_field :fans_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/photos" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#photos_filters">
  Show filters
</a>

app/views/photos/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Photo #<%= @photo.id %>
      </h2>

      <div class="card-body">
        <%= render "form", photo: @photo %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Photos

      <%= link_to new_photo_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "photos/photos_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "photos/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Photos

        <%= link_to new_photo_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @photos, partial: "list_item", as: :photo %>
      </div>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Photo
      </h2>

      <div class="card-body">
        <%= render "form", photo: @photo %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @photo, partial: "card", as: :photo %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "photos/photo_likes" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "photos/photo_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "photos/photo_commenters" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "photos/photo_fans" %>
  </div>
</div>