config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :friend_requests

      resources :comments

      resources :votes

      resources :photos

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "photos#index"
  resources :friend_requests
  resources :comments
  resources :votes
  resources :photos
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  enum status: { "accepted" => 0, "pending" => 1 }

  # Direct associations

  belongs_to :accepted_sender,
             class_name: "User",
             foreign_key: "sender_id",
             counter_cache: :accepted_sent_friend_requests_count

  belongs_to :recipient,
             class_name: "User",
             counter_cache: :received_friend_requests_count

  belongs_to :sender,
             class_name: "User",
             counter_cache: :sent_friend_requests_count

  # Indirect associations

  # Validations

  validates :recipient_id, uniqueness: { scope: [:sender_id], message: "already requested" }

  validates :recipient_id, presence: true

  validates :sender_id, presence: true

  validates :status, presence: true

  validates :status, inclusion: { in: ["pending", "accepted", "declined"] }

  # Scopes

  scope :first_scope, -> { where("friend_requests.updated_at >= :query", query: "2020-08-01T12:00:00+00:00") }

  def to_s
    sender.to_s
  end
end

app/controllers/api/v1/friend_requests_controller.rb
class Api::V1::FriendRequestsController < Api::V1::GraphitiController
  def index
    friend_requests = FriendRequestResource.all(params)
    respond_with(friend_requests)
  end

  def show
    friend_request = FriendRequestResource.find(params)
    respond_with(friend_request)
  end

  def create
    friend_request = FriendRequestResource.build(params)

    if friend_request.save
      render jsonapi: friend_request, status: :created
    else
      render jsonapi_errors: friend_request
    end
  end

  def update
    friend_request = FriendRequestResource.find(params)

    if friend_request.update_attributes
      render jsonapi: friend_request
    else
      render jsonapi_errors: friend_request
    end
  end

  def destroy
    friend_request = FriendRequestResource.find(params)

    if friend_request.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: friend_request
    end
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :current_user_must_be_friend_request_sender, only: %i[edit update destroy]

  before_action :set_friend_request, only: %i[show edit update destroy]

  def index
    @q = current_user.sent_friend_requests.ransack(params[:q])
    @friend_requests = @q.result(distinct: true).includes(:sender, :recipient, :accepted_sender).page(params[:page]).per(10)
  end

  def show; end

  def new
    @friend_request = FriendRequest.new
  end

  def edit; end

  def create
    @friend_request = FriendRequest.new(friend_request_params)

    if @friend_request.save
      message = "FriendRequest was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @friend_request, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @friend_request.update(friend_request_params)
      redirect_to @friend_request, notice: "Friend request was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @friend_request.destroy
    message = "FriendRequest was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to friend_requests_url, notice: message
    end
  end

  private

  def current_user_must_be_friend_request_sender
    set_friend_request
    unless current_user == @friend_request.sender
      redirect_back fallback_location: root_path, alert: "You are not authorized for that."
    end
  end

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end

  def friend_request_params
    params.require(:friend_request).permit(:sender_id, :recipient_id, :status)
  end
end

app/views/friend_requests/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Friend Request #<%= friend_request.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Sender</dt>
      <dd><%= friend_request.sender_id %></dd>

      <dt>Recipient</dt>
      <dd><%= friend_request.recipient_id %></dd>

      <dt>Status</dt>
      <dd><%= friend_request.status %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back friend_request, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @friend_request.sender %>
          <%= link_to edit_friend_request_url(friend_request), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @friend_request.sender %>
          <%= link_to friend_request, method: :delete, data: { confirm: "Do you really want to delete this friend_request?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(friend_request.updated_at) %> ago
  </div>
</div>

app/views/friend_requests/_form.html.erb
<% was_validated = friend_request.errors.any? %>

<%= form_with(model: friend_request, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :sender_id, value: current_user.id %>
  <div class="form-group">
    <% recipient_class = "form-control" %>
    <% recipient_was_invalid = friend_request.errors.include?(:recipient) %>

    <% if was_validated %>
      <% if recipient_was_invalid %>
        <% recipient_class << " is-invalid" %>
      <% else %>
        <% recipient_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :recipient_id %>
    <%= f.collection_select :recipient_id, User.all, :id, :to_s, {}, class: recipient_class %>
    <% if recipient_was_invalid %>
      <% friend_request.errors.full_messages_for(:recipient).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = friend_request.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status %>
    <%= f.select :status, options_for_select(FriendRequest.statuses.keys), {}, class: "form-control" %>
    <% if status_was_invalid %>
      <% friend_request.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/friend_requests/_friend_requests_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "friend_requests_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :sender_first_name_cont, "User first_name contains" %>
    <%= f.text_field :sender_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :recipient_first_name_cont, "User first_name contains" %>
    <%= f.text_field :recipient_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :accepted_sender_first_name_cont, "User first_name contains" %>
    <%= f.text_field :accepted_sender_first_name_cont, :class => "form-control", :placeholder => "User first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/friend_requests" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#friend_requests_filters">
  Show filters
</a>

app/views/friend_requests/_list_item.html.erb
<%= link_to friend_request, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= friend_request.to_s %>
    <small class="text-muted">
      <%= time_ago_in_words(friend_request.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/friend_requests/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Friend Request #<%= @friend_request.id %>
      </h2>

      <div class="card-body">
        <%= render "form", friend_request: @friend_request %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/friend_requests/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Friend Requests

      <%= link_to new_friend_request_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "friend_requests/friend_requests_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Friend Requests

        <%= link_to new_friend_request_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @friend_requests, partial: "list_item", as: :friend_request %>
      </div>
    </div>
  </div>
</div>

app/views/friend_requests/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Friend Request
      </h2>

      <div class="card-body">
        <%= render "form", friend_request: @friend_request %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/friend_requests/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @friend_request, partial: "card", as: :friend_request %>
  </div>
</div>